# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI\ClientWindow_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowOpacity(1.5)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: rgba(255, 255, 255,30);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setStyleSheet("background-color: rgba(32, 32, 32, 200);\n"
"border-radius: 10px;")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalFrame.setStyleSheet("background-color: rgba(32, 32, 32, 127);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame)
        self.horizontalFrame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 2px solid rgb(0, 0, 0);")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_user_icon = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.pushButton_user_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_user_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_user_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\GUI\\../../../.designer/backup/user_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_user_icon.setIcon(icon)
        self.pushButton_user_icon.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_user_icon.setObjectName("pushButton_user_icon")
        self.horizontalLayout_2.addWidget(self.pushButton_user_icon)
        self.label_user_name = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_user_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.label_user_name.setObjectName("label_user_name")
        self.horizontalLayout_2.addWidget(self.label_user_name)
        self.verticalLayout.addWidget(self.horizontalFrame_2)
        self.lineEdit_chat_search = QtWidgets.QLineEdit(self.verticalFrame)
        self.lineEdit_chat_search.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 2px solid rgb(0, 0, 0);")
        self.lineEdit_chat_search.setObjectName("lineEdit_chat_search")
        self.verticalLayout.addWidget(self.lineEdit_chat_search)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.verticalFrame)
        self.scrollArea_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 182, 441))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.horizontalFrame_3.setGeometry(QtCore.QRect(10, 20, 160, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 50))
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.label_4.setPixmap(QtGui.QPixmap(".\\GUI\\../../../.designer/backup/users_icon.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.verticalFrame1 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame1.setStyleSheet("background-color: rgba(32, 32, 32, 63);")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame_21 = QtWidgets.QFrame(self.verticalFrame1)
        self.horizontalFrame_21.setStyleSheet("background-color: rgba(0, 0, 0, 20);\n"
"border: 2px solid rgb(0, 0, 0);")
        self.horizontalFrame_21.setObjectName("horizontalFrame_21")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_21)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_chat_icon = QtWidgets.QPushButton(self.horizontalFrame_21)
        self.pushButton_chat_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_chat_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_chat_icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\GUI\\../../../.designer/backup/users_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_chat_icon.setIcon(icon1)
        self.pushButton_chat_icon.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_chat_icon.setObjectName("pushButton_chat_icon")
        self.horizontalLayout_3.addWidget(self.pushButton_chat_icon)
        self.label_chat_name = QtWidgets.QLabel(self.horizontalFrame_21)
        self.label_chat_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        self.label_chat_name.setObjectName("label_chat_name")
        self.horizontalLayout_3.addWidget(self.label_chat_name)
        self.pushButton_chat_settings = QtWidgets.QPushButton(self.horizontalFrame_21)
        self.pushButton_chat_settings.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_chat_settings.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_chat_settings.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: none;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\GUI\\../../../.designer/backup/settings_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_chat_settings.setIcon(icon2)
        self.pushButton_chat_settings.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_chat_settings.setObjectName("pushButton_chat_settings")
        self.horizontalLayout_3.addWidget(self.pushButton_chat_settings)
        self.verticalLayout_2.addWidget(self.horizontalFrame_21)
        self.textBrowser_chat = QtWidgets.QTextBrowser(self.verticalFrame1)
        self.textBrowser_chat.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(0, 0, 0);")
        self.textBrowser_chat.setObjectName("textBrowser_chat")
        self.verticalLayout_2.addWidget(self.textBrowser_chat)
        self.horizontalFrame1 = QtWidgets.QFrame(self.verticalFrame1)
        self.horizontalFrame1.setStyleSheet("background-color: rgba(0, 0, 0, 40);\n"
"")
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_add_file = QtWidgets.QPushButton(self.horizontalFrame1)
        self.pushButton_add_file.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_add_file.setObjectName("pushButton_add_file")
        self.horizontalLayout_5.addWidget(self.pushButton_add_file)
        self.lineEdit_input = QtWidgets.QLineEdit(self.horizontalFrame1)
        self.lineEdit_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 10);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout_5.addWidget(self.lineEdit_input)
        self.pushButton_send = QtWidgets.QPushButton(self.horizontalFrame1)
        self.pushButton_send.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_5.addWidget(self.pushButton_send)
        self.verticalLayout_2.addWidget(self.horizontalFrame1)
        self.horizontalLayout.addWidget(self.verticalFrame1)
        self.gridLayout.addWidget(self.horizontalFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_user_name.setText(_translate("MainWindow", "My_name"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_chat_name.setText(_translate("MainWindow", "Chat_name"))
        self.textBrowser_chat.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_add_file.setText(_translate("MainWindow", "Add File"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.pushButton_send.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
